services:
  mysql-planner:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planner
    volumes:
      - ./1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./2-inserts.sql:/docker-entrypoint-initdb.d/2-inserts.sql